//Browser
browser = chrome
//URL
url = https://www.demoblaze.com/#

username = Pugazh
password = Welcome@22
location = \\ScreenShot\\

//orderDetails

ordername = pugazh
contry = India
city = chennai
card = 4111111111
month = May
year = 2026
